### ISSUE TITLE
Script Runner doesn't run PowerShell script

### ISSUE THREAD

**Issue by Luksys5** [Chaser324/unity-build-actions#12]
Hey,
I have a script and I call it with post build actions. The problem is that it opens file in notepad and doesn't run it normally
I have tried with single path separator(\) and double path separator(\\) but results are still same

Thanks for any help

![image](https://user-images.githubusercontent.com/6574283/51438395-4e02ad00-1cb4-11e9-95e9-2f260d8e40ed.png)

![image](https://user-images.githubusercontent.com/6574283/51438440-e00ab580-1cb4-11e9-91f3-dd58b12eddbb.png)

**Comment by Chaser324** [comment]
If you double clicked on a .ps1 file, it would also likely open in
Notepad. So, this is kinda the expected behavior. If you want to execute
the script instead, you'll either need to setup your system to execute .ps1
files by default or take a different approach with the script runner.

Try specifying the script path as the path to the Powershell
executable (C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe)
and your script as an argument. You could also possibly create a .bat file
that starts your PS script and execute that.
